### ISSUE TITLE
Mancanze

### ISSUE THREAD

**Issue by AntonioMoscat** [Web-Rats/BackEnd#7]
Mancano le funzione di richiesta dati (find(...)) nel file del db. 
Senza non posso controllare se i dati sono già presenti nel db prima di andarli a richiedere nuovamente all'API #6

**Comment by FabioMusi04** [comment]
**Confermo.**

> Mancano le funzione di richiesta dati (find(...)) nel file del db. Senza non posso controllare se i dati sono già presenti nel db prima di andarli a richiedere nuovamente all'API #6

**Comment by Giacomo-Cattani** [comment]
Confermo Appieno.
> Mancano le funzione di richiesta dati (find(...)) nel file del db. Senza non posso controllare se i dati sono già presenti nel db prima di andarli a richiedere nuovamente all'API #6

10/10

**Comment by Giacomo-Cattani** [comment]
![697b023b-64a5-49a0-8059-27b963453fb1](https://github.com/Web-Rats/BackEnd/assets/151133021/b94eaf80-b3c2-4718-94b8-a2ff95c5b59c)

> **Confermo.**
> 
> > Mancano le funzione di richiesta dati (find(...)) nel file del db. Senza non posso controllare se i dati sono già presenti nel db prima di andarli a richiedere nuovamente all'API #6

**Comment by AntonioMoscat** [comment]
Close
